//This file contains the private characters used in bitmark
const private_char_map = {
  schutzklasse_1: " ",
  U_e003: " ",
  U_e004: " ",
  U_e005: " ",
  U_e006: " ",
  U_e007: " ",
  nin: " ",
  nint: " ",
  cd: " ",
  U_e00a: " ",
  U_e00b: " ",
  pen: " ",
  n: " ",
  pe: " ",
  U_e00f: " ",
  U_e010: " ",
  U_e011: " ",
  U_e012: " ",
  U_e013: " ",
  U_e014: " ",
  konformitaetszeichen: " ",
  neutralleiter: " ",
  schutzleiter: " ",
  erforderlich: " ",
  richtig: " ",
  verweis: " ",
  compact: " ",
  U_e01c: " ",
  U_e01d: " ",
  U_e01e: " ",
  U_e01f: " ",
  U_e020: " ",
  U_e021: " ",
  U_e022: " ",
  U_e023: " ",
  U_e024: " ",
  schutzklasse_3: " ",
  U_e026: " ",
  U_e027: " ",
  U_e028: " ",
  U_e029: " ",
  U_e02a: " ",
  U_e02b: " ",
  U_e02c: " ",
  U_e02d: " ",
  U_e02e: " ",
  U_e02f: " ",
  flagge: " ",
  sonderisoliert: " ",
  profi_tipp: " ",
  U_e033: " ",
  U_e034: " ",
  U_e035: " ",
  U_e036: " ",
  U_e037: " ",
  U_e038: " ",
  U_e039: " ",
  U_e03a: " ",
  U_e03b: " ",
  U_e03c: " ",
  U_e03d: " ",
  U_e03e: " ",
  U_e03f: " ",
  U_e040: " ",
  U_e041: " ",
  U_e042: " ",
  pen_leiter: " ", //kommt 2x vor welcher ist richtig?
  U_e044: " ",
  U_e045: " ",
  U_e046: " ",
  U_e047: " ",
  U_e048: " ",
  U_e049: " ",
  U_e04a: " ",
  U_e04b: " ",
  U_e04c: " ",
  U_e04d: " ",
  sicherheitszeichen: " ",
  erdung: " ",
  ch: " ",
  U_e051: " ",
  U_e052: " ",
  U_e053: " ",
  U_e054: " ",
  qualitaetszeichen: " ",
  U_e056: " ",
  U_e057: " ",
  fl_armatur: " ",
  regensicher: " ",
  rcd: " ",
  selektiver_rcd: " ",
  nibt: " ",
  potenzialausgleich: " ",
  kein_schutzleiter: " ",
  U_e05f: " ",
  oberflaechentemp_110: " ",
  geschuetzter_trafo: " ",
  korosionssicher: " ",
  wasseraustrittsstelle: " ",
  kaeltebestaendig: " ",
  U_e065: " ",
  U_e066: " ",
  U_e067: " ",
  U_e068: " ",
  explosionssicher: " ",
  U_e06a: " ",
  U_e06b: " ",
  staubgeschuetzt: " ",
  staubdicht: " ",
  schalter: " ",
  unendlich: " ",
  nicht_entflammbar: " ",
  moebelleuchte: " ",
  normal_entflammbar: " ",
  blitzpfeil: " ",
  tropfwassersicher: " ",
  spritzwassersicher: " ",
  steckdose_schutzkontakt: " ",
  steckdose: " ",
  verteiler: " ",
  typ_a: " ",
  unterspannungsausloesung: " ",
  zus_erdungsschiene: " ",
  haupterdungsschiene: " ",
  erdungsschiene: " ",
  leiter: " ",
  aussenleiter: " ", // same as above
  sicherung: " ",
  trennklemme: " ",
  trennstelle: " ",
  trenner: " ",
  U_e083: " ",
  transformator: " ",
  trafo: " ",
  trenntrafo: " ",
  kurzschlussfest: " ", //?? löschen?
  trafo_kurzschlussfest: " ", // same as above
  steuertransformator: " ",
  sicherheitstrafo: " ",
  schlaufdose: " ",
  umhuellung: " ",
  kurzzeitverzoegerter: " ",
  kurzzeitverzoegert: " ",
  kaeltebestaendig: " ",
  widerstand: " ",
  spannungsfuehrend: " ",
  getrennte_wicklungen: " ",
  trafo_getrennte_wicklung: " ",
  kurzschlussfest: " ",
  unzulaessig: " ",
  wechselstrom: " ",
  U_e096: " ",
  U_e097: " ",
  U_e098: " ",
  U_e099: " ",
  material: " ",
  typ_ac: " ",
  oberflaechentemp_130: " ",
  psa_1: " ",
  empfohlen: " ",
  hand: " ",
  schutzhelm: " ",
  psa_2: " ",
  leuchtenschutz: " ",
  eingebautes_zuendgeraet: " ",
  einbauleuchte_isoliermaterial: " ",
  U_e0a5: " ",
  vorschaltgeraet: " ",
  nicht_it: " ",
  nicht_empfohlen: " ",
  rauerbetrieb: " ",
  psa_3: " ",
  gleichstromsensitiv: " ",
  begrenzte_oberflaechentemp: " ",
  egrenzte_oberflaechentemp: " ", // same as above, falsch geschrieben in Quelle
  U_e0ad: " ",
  U_e0ae: " ",
  zulaessig: " ",
  nicht_moeglich: " ",
  aussenleiter: " ",
  neutralleiter_n: " ",
  schutzleiter_pe: " ",
  systemreferenzleiter: " ",
  // pen_leiter: " ", doppelte bezeichnung, sonderfall
  nr_1: " ",
  nr_2: " ",
  nr_3: " ",
  nr_4: " ",
  energiebegrenzungsklasse_3: " ",
  symbol_ip55: " ",
  kontrolle_inspektionsstelle: " ",
  kontrolle_kontrollorgan_blau: " ",
  symbol_rot: " ",
  kontrolle_kontrollorgan: " ",
  kurzzeitverzoegerter_rcd: " ",
  gelbe_box: " ",
};

/*
zulaessig U+e0af
nicht_moeglich U+e0b0
Aussenleiter ---> sieht gleich aus wie 'leiter'
Neutralleiter_N U+e0b2
PEN_Leiter U+e0b6
Schutzleiter_PE U+e0b3
Systemreferenzleiter U+e0b4
egrenzte_oberflaechentemp --> schon vorhanden U_e0ac egrenzte-oberflaechentemp -->  <private-char description="egrenzte-oberflaechentemp">
Nr_1 U+e0b7
Nr_2 U+e0b8
Nr_3 U+e0b9
Nr_4  U+e0ba
Energiebegrenzungsklasse_3 U+e0bb
*/

module.exports = private_char_map;
